services:
    pg_shard1:
        image: postgres:15
        container_name: pg_shard1
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: shard1_db
        ports:
            - "5433:5432"
        volumes:
            - ./shard1:/docker-entrypoint-initdb.d

    pg_shard2:
        image: postgres:15
        container_name: pg_shard2
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: shard2_db
        ports:
            - "5434:5432"
        volumes:
            - ./shard2:/docker-entrypoint-initdb.d

    pg_shard3:
        image: postgres:15
        container_name: pg_shard3
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: shard3_db
        ports:
            - "5435:5432"
        volumes:
            - ./shard3:/docker-entrypoint-initdb.d

    pg_shard4:
        image: postgres:15
        container_name: pg_shard4
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: shard4_db
        ports:
            - "5436:5432"
        volumes:
            - ./shard4:/docker-entrypoint-initdb.d

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - pg_shard1
            - pg_shard2
            - pg_shard3
            - pg_shard4

    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        depends_on:
            - pg_shard1
            - pg_shard2
            - pg_shard3
            - pg_shard4
        volumes:
            - grafana-storage:/var/lib/grafana

volumes:
    grafana-storage:
