AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Docker for PostgreSQL Sharding Project

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH into the instance

Resources:
  ShardedPostgresInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      KeyName: !Ref KeyName
      ImageId: ami-0dc0ac921efee9f9d # Ubuntu 22.04 LTS in eu-west-1
      SecurityGroups:
        - !Ref ShardedSecurityGroup
      Tags:
        - Key: Name
          Value: postgres-shard-node
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install -y docker.io docker-compose git
          sudo usermod -aG docker ubuntu
          git clone https://github.com/konomissira/airbnb_sharding_project.git /home/ubuntu/shard-project
          cd /home/ubuntu/shard-project/docker
          cp .env.example .env
          docker-compose up -d

  ShardedSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and local-only ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # SSH from anywhere
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5435
          CidrIp: 127.0.0.1/32  # Local-only access for PostgreSQL shards
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 127.0.0.1/32  # Local-only access for pgAdmin
      Tags:
        - Key: Name
          Value: postgres-shard-sg

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt ShardedPostgresInstance.PublicIp
